name: 'Operate K6 CRD'
description: 'Create and delete K6 Custom Resource Definitions to Kubernetes Cluster'
author: 'ymktmk'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'k6'
  color: 'orange'
inputs:
  method:
    description: 'set create or delete'
    required: true
  vus:
    description: 'vus'
    required: false
    default: ''
  duration: 
    description: 'duration'
    required: false
    default: ''
  rps:
    description: 'rps'
    required: false
    default: ''
  parallelism: 
    description: 'parallelism'
    required: false
    default: ''
  template_file:
    description: 'k6 template file path'
    required: true
